'use client';

import { ConsultationReport } from '@/types';

interface ReportPreviewProps {
  report: ConsultationReport;
  onDownload: () => void;
}

export default function ReportPreview({ report, onDownload }: ReportPreviewProps) {
  return (
    <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-sm mb-6 msg-animate max-w-[90%] mx-auto overflow-hidden">
      <div className="flex items-center justify-between mb-4 pb-4 border-b border-slate-100">
        <div>
          <h3 className="text-sm font-bold text-slate-900">Health Consultation Report</h3>
          <p className="text-[10px] text-slate-400">Generated by Ada Health AI</p>
        </div>
        <div className="w-10 h-10 bg-emerald-50 rounded-full flex items-center justify-center text-xl">
          📄
        </div>
      </div>

      <div className="space-y-4">
        <section>
          <h4 className="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-1">Assessment</h4>
          <p className="text-xs text-slate-700 leading-relaxed">
            Based on your reports, this may indicate <span className="font-semibold">{report.possibleConditions.join(', ')}</span>.
          </p>
        </section>

        <section>
          <h4 className="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-1">Key Recommendation</h4>
          <p className="text-xs text-slate-700 leading-relaxed">
            {report.medications} and {report.homeCare}.
          </p>
        </section>

        <section className="bg-red-50 p-3 rounded-xl border border-red-100">
          <h4 className="text-[10px] font-bold text-red-600 uppercase tracking-wider mb-1">Red Flags</h4>
          <ul className="text-[11px] text-red-700 space-y-1">
            {report.redFlags.slice(0, 2).map((flag, i) => (
              <li key={i}>• {flag}</li>
            ))}
          </ul>
        </section>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mt-6">
        <button
          onClick={onDownload}
          className="flex items-center justify-center gap-2 py-2.5 bg-[#2D5A27] text-white rounded-xl text-xs font-bold hover:bg-emerald-900 transition-colors shadow-sm"
        >
          ⬇️ Download PDF
        </button>
        <button
          onClick={() => window.print()}
          className="flex items-center justify-center gap-2 py-2.5 border border-slate-200 text-slate-600 rounded-xl text-xs font-bold hover:bg-slate-50 transition-colors"
        >
          🖨️ Print
        </button>
      </div>
    </div>
  );
}
