import { Response } from 'express';
import { GoogleGenerativeAI } from '@google/generative-ai';
import PDFDocument from 'pdfkit';
import Consultation from '../models/Consultation';
import Report from '../models/Report';
import { AuthRequest } from '../types';

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || '');

export const generateReport = async (req: AuthRequest, res: Response) => {
  const { consultationId } = req.body;

  try {
    const consultation = await Consultation.findById(consultationId);
    if (!consultation) return res.status(404).json({ error: 'Consultation not found' });

    const model = genAI.getGenerativeModel({ 
      model: 'gemini-2.0-flash',
      generationConfig: { responseMimeType: "application/json" }
    });

    const prompt = `Based on this consultation conversation, extract and return ONLY a JSON object with these fields:
    symptoms, duration, triggers, currentMedications, possibleConditions (array), medications, homeCare, adviceDuration, redFlags (array).
    
    Conversation:
    ${consultation.messages.map(m => `${m.role.toUpperCase()}: ${m.content}`).join('\n')}`;

    const result = await model.generateContent(prompt);
    const rawResponse = result.response.text();
    
    let reportData;
    try {
      const cleanedResponse = rawResponse.replace(/```json|```/g, '').trim();
      reportData = JSON.parse(cleanedResponse);
    } catch (e) {
      console.error('[Report AI Parse Error]', e);
      throw new Error('AI failed to generate a structured report');
    }

    // Save report to DB
    const report = await Report.create({
      userId: req.user?._id,
      consultationId: consultation._id,
      title: `Consultation with ${consultation.doctorName}`,
      doctorName: consultation.doctorName,
      content: reportData,
    });

    res.status(201).json(report);
  } catch (error: unknown) {
    console.error(error);
    res.status(500).json({ error: 'Failed to generate report data' });
  }
};

export const downloadReportPdf = async (req: AuthRequest, res: Response) => {
  try {
    const report = await Report.findById(req.params.id);
    if (!report) return res.status(404).json({ error: 'Report not found' });

    const doc = new PDFDocument({ margin: 50 });
    const filename = `ada-report-${report._id}.pdf`;

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);

    doc.pipe(res);

    // PDF Header
    doc.rect(0, 0, 612, 100).fill('#2D5A27');
    doc.fillColor('#FFFFFF').fontSize(20).text('HEALTH CONSULTATION REPORT', 50, 30);
    doc.fontSize(10).text(`Generated by Ada Health AI for ${req.user?.name}`, 50, 55);

    doc.fillColor('#333333').moveDown(4);

    // Content
    const c = report.content;
    doc.fontSize(14).text('ASSESSMENT SUMMARY', { underline: true });
    doc.fontSize(10).moveDown(0.5);
    doc.text(`Doctor: ${report.doctorName}`);
    doc.text(`Symptoms: ${c.symptoms}`);
    doc.text(`Duration: ${c.duration}`);
    doc.moveDown(1.5);

    doc.fontSize(14).text('RECOMMENDATIONS', { underline: true });
    doc.fontSize(10).moveDown(0.5);
    doc.text(`Possible conditions: ${c.possibleConditions?.join(', ')}`);
    doc.text(`Suggested care: ${c.homeCare}`);
    doc.moveDown(1.5);

    doc.fillColor('#B91C1C').fontSize(14).text('RED FLAGS', { underline: true });
    doc.fontSize(10).moveDown(0.5);
    c.redFlags?.forEach((flag: string) => doc.text(`• ${flag}`));

    doc.end();
  } catch (error: unknown) {
    res.status(500).json({ error: 'Failed to generate PDF' });
  }
};

export const getReports = async (req: AuthRequest, res: Response) => {
  try {
    const reports = await Report.find({ userId: req.user?._id }).sort({ createdAt: -1 });
    res.json(reports);
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : 'An unknown error occurred';
    res.status(500).json({ error: message });
  }
};
